```{r}
library('tidyverse')
library('tidytext')
df <- read.csv('/Users/ritaguan/Desktop/r_api.csv')

```

Unique Values in DataFrame
```{r}
df <- unique(df)

```

Remove emoji from DataFrame
```{r}
gsub("[^\x01-\x7F]", "", df$text)

```

Count number of missing value
```{r}
sapply(df, function(x) sum(is.na(x)))

# No missing value (check)
```

Remove unnecessary column from DataFrame
```{r}
df <- subset(df, select = -c(id))

```

Continue Clean Data with RT 
```{r}
gsub("(RT|via)((?:\\b\\W*@\\w+)+)", "", df$text)
```

Remove punctuation from column
```{r}
gsub("[[:punct:]]", "", df$text)
```

Remove customized stopwords
```{r}
delete.stop.words =  function(input.data, stop.words = NULL) {
        
        # is input.data a matrix? a data frame?
        if(is.matrix(input.data) == TRUE | is.data.frame(input.data) == TRUE) {        
                
                # checking if any variables' names exist
                if(length(colnames(input.data)) < 1) {
                        warning(paste("stop word deletion could not be performed:",
                           "\n", "data table does not contain names\n"))

                }
                # checking if the stop words match (any) variables' names
                if(length(stop.words) > 0 && 
                length(intersect(colnames(input.data), stop.words)) == 0) {
                        warning(paste("chosen stop words were not found in the dataset;",
                        "\n", " please check the language, lower/uppercase issues, etc.\n"))                        
                }

                # extracting only those columns that match the remaining names
                culled.data = input.data[,!c(colnames(input.data) %in% stop.words)]
                
        # is input.data a vector?
        } else if(is.vector(input.data) == TRUE) {

                # checking if the stop words match (any) variables' names
                if(length(stop.words) > 0 && 
                length(intersect(input.data, stop.words)) == 0) {
                        warning(paste("chosen stop words were not found in the dataset;",
                        "\n", " please check the language, lower/uppercase issues, etc.\n"))                        
                }

                # extracting only those elements that match the remaining names
                culled.data = input.data[!(input.data %in% stop.words)]
                
        # is input.data a list?
        } else if( inherits(input.data, "stylo.corpus") == TRUE ) {

                # checking if the stop words match (any) variables' names
              #  if(length(stop.words) > 0 && 
              #  length(intersect(input.data, stop.words)) == 0) {
              #          warning(paste("chosen stop words were not found in the dataset;",
              #          "\n", " please check the language, lower/uppercase issues, etc.\n"))                        
              #  }

                # function for extracting the desired words
                extract.words = function(x, words) x[!(x %in% words)] 
                # and the procedure of extracting the words itself
                culled.data = lapply(input.data, extract.words, words = stop.words)
                class(culled.data) = "stylo.corpus"
                
        } else {
                warning(paste("chosen stop words could not be applied to the dataset:",
                          "\n"," unrecognized data structure\n"))
                culled.data = NULL
        }

return(culled.data)
}



delete.stop.words(df$text, stop.words = c('hi',"it's", 'it’s', "i'm", 'i’m', 'im', 'want', 'like', '$', '@', 'rt'))


```

Print out DataFrame
```{r}
print(df)
```

Get New CSV Data
```{r}
write.csv(df,"/Users/ritaguan/Desktop/cleaned_r.csv", row.names = FALSE)


```